services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_practicum
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Prokhorsdz1234